//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewDayAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientRecipe
    {
        public int ID { get; set; }
        public Nullable<int> IdRecipes { get; set; }
        public Nullable<int> IdIngredients { get; set; }
        public Nullable<double> AbsolutQuantity { get; set; }
        public string AbsolutUnitMeasure { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Recipies Recipies { get; set; }
    }
}
